/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FoodId = IDL.Nat;
export const ReviewStats = IDL.Record({
  'count' : IDL.Nat,
  'average' : IDL.Float64,
  'foodId' : FoodId,
});
export const Timestamp = IDL.Nat;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'foodId' : FoodId,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat,
  'foodId' : FoodId,
});
export const SuggestionCategory = IDL.Variant({
  'topic' : IDL.Null,
  'internationalFood' : IDL.Null,
  'websiteImprovement' : IDL.Null,
  'filipinoFood' : IDL.Null,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'category' : SuggestionCategory,
});
export const CommentInput = IDL.Record({
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'foodId' : FoodId,
});
export const ReviewInput = IDL.Record({
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat,
  'foodId' : FoodId,
});
export const SuggestionInput = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'category' : SuggestionCategory,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReviewStats' : IDL.Func([IDL.Nat], [ReviewStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'listExplored' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'listFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'listReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
  'markExplored' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitComment' : IDL.Func([CommentInput], [Comment], []),
  'submitReview' : IDL.Func([ReviewInput], [Review], []),
  'submitSuggestion' : IDL.Func([SuggestionInput], [Suggestion], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FoodId = IDL.Nat;
  const ReviewStats = IDL.Record({
    'count' : IDL.Nat,
    'average' : IDL.Float64,
    'foodId' : FoodId,
  });
  const Timestamp = IDL.Nat;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'foodId' : FoodId,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat,
    'foodId' : FoodId,
  });
  const SuggestionCategory = IDL.Variant({
    'topic' : IDL.Null,
    'internationalFood' : IDL.Null,
    'websiteImprovement' : IDL.Null,
    'filipinoFood' : IDL.Null,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'category' : SuggestionCategory,
  });
  const CommentInput = IDL.Record({
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'foodId' : FoodId,
  });
  const ReviewInput = IDL.Record({
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat,
    'foodId' : FoodId,
  });
  const SuggestionInput = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'category' : SuggestionCategory,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReviewStats' : IDL.Func([IDL.Nat], [ReviewStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'listExplored' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'listFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'listReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
    'markExplored' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitComment' : IDL.Func([CommentInput], [Comment], []),
    'submitReview' : IDL.Func([ReviewInput], [Review], []),
    'submitSuggestion' : IDL.Func([SuggestionInput], [Suggestion], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };