/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Comment {
  'id' : bigint,
  'createdAt' : Timestamp,
  'text' : string,
  'authorName' : string,
  'foodId' : FoodId,
}
export interface CommentInput {
  'text' : string,
  'authorName' : string,
  'foodId' : FoodId,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FoodId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Review {
  'id' : bigint,
  'createdAt' : Timestamp,
  'text' : string,
  'reviewerName' : string,
  'rating' : bigint,
  'foodId' : FoodId,
}
export interface ReviewInput {
  'text' : string,
  'reviewerName' : string,
  'rating' : bigint,
  'foodId' : FoodId,
}
export interface ReviewStats {
  'count' : bigint,
  'average' : number,
  'foodId' : FoodId,
}
export interface Suggestion {
  'id' : bigint,
  'name' : [] | [string],
  'createdAt' : Timestamp,
  'text' : string,
  'category' : SuggestionCategory,
}
export type SuggestionCategory = { 'topic' : null } |
  { 'internationalFood' : null } |
  { 'websiteImprovement' : null } |
  { 'filipinoFood' : null };
export interface SuggestionInput {
  'name' : [] | [string],
  'text' : string,
  'category' : SuggestionCategory,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
/**
 * / LASA composition root: owns stable state and wires domain mixins.
 * / No business logic lives here — every endpoint is delegated to a mixin.
 */
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Average rating and review count for one food.
   */
  'getReviewStats' : ActorMethod<[bigint], ReviewStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all comments, newest first.
   */
  'listComments' : ActorMethod<[], Array<Comment>>,
  /**
   * / List the caller's explored food ids.
   */
  'listExplored' : ActorMethod<[], Array<bigint>>,
  /**
   * / List the caller's favorite food ids.
   */
  'listFavorites' : ActorMethod<[], Array<bigint>>,
  /**
   * / List all submitted reviews, newest first.
   */
  'listReviews' : ActorMethod<[], Array<Review>>,
  /**
   * / List all submitted suggestions, newest first.
   */
  'listSuggestions' : ActorMethod<[], Array<Suggestion>>,
  /**
   * / Mark a food as explored for the caller; returns the new state.
   */
  'markExplored' : ActorMethod<[bigint], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Leave a food-related comment.
   */
  'submitComment' : ActorMethod<[CommentInput], Comment>,
  /**
   * / Submit a review with a 1-5 star rating, reviewer name, and review text.
   */
  'submitReview' : ActorMethod<[ReviewInput], Review>,
  /**
   * / Submit a food, topic, or website-improvement suggestion.
   */
  'submitSuggestion' : ActorMethod<[SuggestionInput], Suggestion>,
  /**
   * / Toggle a food as favorite for the caller; returns the new state.
   */
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];